[package]
name = "xim"
version = "0.1.0"
authors = ["raylax <raylax@inurl.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = { path = "components/websocket", default-features = false }